### ISSUE TITLE
CNAME not resolve

### ISSUE THREAD

**Issue by EasonWang01** [mailgun/mailgun-go#106]
Cause not response from support so ask here.Any configuration wrong?

<img width="420" alt="21" src="https://cloud.githubusercontent.com/assets/11001914/26527800/649dc2b8-43ce-11e7-96cb-b97971624889.png">
<img width="564" alt="22" src="https://cloud.githubusercontent.com/assets/11001914/26527801/65ffdcc2-43ce-11e7-8a68-01b5b6be5a78.png">

**Comment by mbanzon** [comment]
Mailgun support is the correct place to ask. It looks fine to me (fwiw).
