### ISSUE TITLE
EmailValidation Update

### ISSUE THREAD

**Issue by cicerocomp** [mailgun/mailgun-go#109]
New features have been added, and now the api is paid for:
http://blog.mailgun.com/mailgun-rolls-out-changes-to-email-validation-api-including-new-pricing-model-and-features/

New return: 
```json
{
    "address": "foo@mailgun.net",
    "did_you_mean": null,
    "is_disposable_address": false,
    "is_role_address": true,
    "is_valid": true,
    "parts": {
        "display_name": null,
        "domain": "mailgun.net",
        "local_part": "foo"
    }
}
```
http://mailgun-documentation.readthedocs.io/en/latest/api-email-validation.html

**Comment by lyoshenka** [comment]
It's been almost two months. Any idea when this will be included?

**Comment by thrawn01** [comment]
Thanks for bringing this up again, I'll put in on the board next week.

**Comment by lyoshenka** [comment]
@thrawn01 any updates?

**Comment by thrawn01** [comment]
It's looking like a few more weeks before I have time to work on this. In the middle of a major project.

**Comment by lyoshenka** [comment]
@thrawn01 can you please merge the above PR or let us know what else is necessary to make this happen?

**Comment by mbanzon** [comment]
@thrawn01 have this been resolved or am I missing something?

**Comment by thrawn01** [comment]
@mbanzon I've added verification changes to the v2 release PR. I've not had time to complete the work. Some fields are probably still missing. If you wanna take a stab at it please do.
