### ISSUE TITLE
 invalid character 'M' looking for beginning of value

### ISSUE THREAD

**Issue by dadatawajue** [mailgun/mailgun-go#110]
Hello, I'm trying to get mailgun to work with my Go project, but for some reason it's not working, and I'm not sure what I might be doing wrong.

I've tested my API key using the curl command as described in the official documentation:

```
curl -s --user 'api:YOUR_API_KEY' \
    https://api.mailgun.net/v3/YOUR_DOMAIN_NAME/messages \
    -F from='Excited User <mailgun@YOUR_DOMAIN_NAME>' \
    -F to=YOU@YOUR_DOMAIN_NAME \
    -F to=bar@example.com \
    -F subject='Hello' \
    -F text='Testing some Mailgun awesomness!'
```

If I replace YOUR_API_KEY and YOUR_DOMAIN_NAME then it works and I get the expected json response:

```
{
  "id": "<20170715XXXXXX.XXXXX.XXXXXXXXXXXXXXX@MY_DOMAIN_NAME>",
  "message": "Queued. Thank you."
}
```

As for the mailgun-go library, this is my code:

```
import (
    "gopkg.in/mailgun/mailgun-go.v1"
)

...

domain := "https://api.mailgun.net/v3/MY_DOMAIN_NAME/messages"
APIKey := "key-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" // 32 chars long
publicAPIKey := "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" // 32 chars long but different from the above APIKey

mg := mailgun.NewMailgun(domain, APIKey, publicAPIKey)
message := mailgun.NewMessage(
	"Fancy subject!",
	"sender@example.com",
	"Hello from Mailgun Go!",
	"myemail@gmail.com")
resp, id, err := mg.Send(message)
if err != nil {
	log.Println("error:", err)
}
fmt.Printf("ID: %s Resp: %s\n", id, resp)
```

and the response:

```
error: invalid character 'M' looking for beginning of value
ID:  Resp: 
```

I have also tried changing "`https://api.mailgun.net/v3/MY_DOMAIN_NAME/messages`" to "`https://api.mailgun.net/v3/MY_DOMAIN_NAME`" but it resulted in same error. Also, I'm not quite sure why I only need 1 API Key when using CURL but 2 API Keys when using this library (I assume it's in order to unlock other features unrelated to sending email? but I guess it's not important).. 

Any help would be much appreciated :)

**Comment by lukaszatsagan** [comment]
Domain should be the mailgun domain you're using (i.e. the `YOUR_DOMAIN_NAME`) part. That's causing your error.

Also, double check the order of arguments to `NewMessage`.

**Comment by dadatawajue** [comment]
oh wow, I could have sworn I tried to do that before as well and received similar error message.. but it seems to be working after following your instructions.. thanks a lot <3
