### ISSUE TITLE
While send .csv using mailgun. We get an empty file.

### ISSUE THREAD

**Issue by aman-daffodil** [mailgun/mailgun-go#111]
Hello 
I am sending .csv file using mailgun-go. The mail is succesfully sent with the attachment but when i open the file, it is empty on contrary if i open the file that was uploaded (present on my local system) it has data with it. 
This scenario happens for only .csv files as if i send .txt or .png files it sends it and also the data is accurate.

Thanks

**Comment by mbanzon** [comment]
@aman-daffodil I know this is a bit overdue - but are you still able to reproduce this??

**Comment by mbanzon** [comment]
@thrawn01 have you looked at this?

To me this sounds a bit more like a case of an overly aggressive mailserver receiving the message. I haven't done any formal tests but I am using the library and Mailgun to send all sorts of files on a daily basis with no known issue so far.

Can we close this?

**Comment by thrawn01** [comment]
I'll close this. We can re-open if someone has the same issue.

**Comment by burakuyar** [comment]
Hi @thrawn01 ,
I am having the same issue. Did you have any solutions meanwhile?
