### ISSUE TITLE
Message Variables sent with the go-client does not support arbitrary JSON

### ISSUE THREAD

**Issue by kdparker** [mailgun/mailgun-go#112]
To demonstrate I added a test to the end of messages_test here: https://github.com/kdparker/mailgun-go/blob/master/messages_test.go#L387

When you run this (with different orders of the actual tests) you get: 
```
--- FAIL: TestSendMGMessageVariables (0.00s)
       messages_test.go:414: expected these to be equal:
		ACTUAL:
		(string) (len=14) "{\"test\":\"123\"}"

		EXPECTED:
		(map[string]string) (len=1) {
		 (string) (len=4) "test": (string) (len=3) "123"
		}
```
```
--- FAIL: TestSendMGMessageVariables (0.00s)
       messages_test.go:414: expected these to be equal:
		ACTUAL:
		(string) (len=5) "false"

		EXPECTED:
		(bool) false
```
```
--- FAIL: TestSendMGMessageVariables (0.00s)
       messages_test.go:414: expected these to be equal:
		ACTUAL:
		(string) (len=14) "\"test-str-val\""

		EXPECTED:
		(string) (len=12) "test-str-val"
```

We noticed this error initially when noticing that when using this client, we were seeing this:
```
"user-variables": {
        "foo": "\"strval1\"",
        "is-test": "true",
        "bar": "\"strval2\"",
        "var": "\"strval3\""
    },
```
instead of my expected:
```
"user-variables": {
        "foo": "strval1",
        "is-test": true,
        "bar": "strval2",
        "var": "strval3"
    },
```

I can maybe help with the patch for this problem, but I first want to see if this behavior is intentional or not?

**Comment by thrawn01** [comment]
This does look like a bug and doesn't appear to be intentional.
http://mailgun-documentation.readthedocs.io/en/latest/user_manual.html#attaching-data-to-messages
