### ISSUE TITLE
Client periodically responds with vague EOF error

### ISSUE THREAD

**Issue by jeveleth** [mailgun/mailgun-go#113]
When I use the GetStatusFromErr() function to check for errors, I periodically get a -1 in return. The error returned by mailgun.Send() in these cases is the following.

```\"Post https://api.mailgun.net/v3/[mymailgundomain]/messages: EOF\"\n"```

This seems like it's the result of an uncaught io.EOF error somewhere. The mailgun-go package should check for that error and return a more helpful error message.

**Comment by thrawn01** [comment]
Pull Requests for this are welcome.

**Comment by thrawn01** [comment]
I suspect the EOF is coming from 

```go
responseBody, err := ioutil.ReadAll(resp.Body)
```
In makeRequest(). I've wrapped the error to provide more information in #149
