### ISSUE TITLE
Route Forward: unmarshalling POST form?

### ISSUE THREAD

**Issue by GoodPete** [mailgun/mailgun-go#115]
Given a forward route, how would one convert that to a `mailgun.Message` or `mailgun.StoredMessage`? More specifically, how do I go from an `*http.Request` to a `mailgun.StoredMessage`?

**Comment by breerly** [comment]
In other words, how do I go from an `*http.Request` to a `mailgun.StoredMessage`?

**Comment by breerly** [comment]
AFAICT, this is the only way:

```go
func Handler(w http.ResponseWriter, r *http.Request) {
    err := r.ParseForm()
    if err != nil {
        log.Fatal(err)
    }

    // contains a net/url.Values with the parsed body
    fmt.Printf("%+v\n", r.PostForm) 
}
```

That can be used with http://www.gorillatoolkit.org/pkg/schema to serialize to a struct:

```go
func Handler(w http.ResponseWriter, r *http.Request) {
    err := r.ParseForm()
    if err != nil {
        log.Fatal(err)
    }

    message := new(ForwardedMessage)
    decoder := schema.NewDecoder()
    decoder.Decode(message, r.PostForm)

    fmt.Printf("%+v\n", message) 
}

type ForwardedMessage struct {
    Recipient string
    Sender    string
}
```

This leads me to believe that this library should provide the struct to deserialize from, instead of having each user manager their own.

Thoughts?

**Comment by thrawn01** [comment]
This would be a nice addition to the library, we would need some good documentation to explain how to use in their own http handlers. Pull Requests for this are welcome.

**Comment by tv42** [comment]
Working without such a struct isn't too bad, either.

```
	ok, err := mg.VerifyWebhookSignature(mailgun.Signature{
		TimeStamp: req.PostForm.Get("timestamp"),
		Token:     req.PostForm.Get("token"),
		Signature: req.PostForm.Get("signature"),
	})
```

```
req.PostForm.Get("body-mime")
```

and so on.

**Comment by gustavomassa** [comment]
This is how we do it, we use a struct that contains all the url.Values from the parsed form. To get the Values we use the Get method from the net/url lib.

```
type NotifyEmailForm struct {
	url.Values
}

func Notify(mailgun umailgun.Mailgun, service Service) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var err error

		ctx, log, end := start(r)
		defer end(w, r.ContentLength, &err)

		r.Body = http.MaxBytesReader(w, r.Body, 15*1048576)
		
		if err = r.ParseForm(); err != nil {
			log.WithError(err).Warn("Failed to parse form")
			w.WriteHeader(http.StatusBadRequest)
			return
		}
		form := umailgun.NotifyEmailForm{Values: r.Form}

		key := form.Get(key)
		uKey := url.QueryUnescape(form.Get(string(key)))
```

Now I'm trying to do the inverse since the Mailgun API returns the stored messages in .json format. How to convert the JSON message to url.Values? Something like doing reverse engineering of the webhook post done by mailgun, but from the API

**Comment by tsidei** [comment]
@gustavomassa you should be able to do something like this:

```go
        msg, err := mg.GetStoredMessage(ctx, messageURL)
	if err != nil {
		log.Fatal(err)
	}

	postForm := &url.Values{}
	postForm.Add("stripped-text", msg.StrippedText)
	postForm.Add("stripped-html", msg.StrippedHtml)
	postForm.Add("body-plain", msg.BodyPlain)
	b, _ := json.Marshal(msg.MessageHeaders)
	postForm.Add("message-headers", string(b))
	...

	req, err := http.NewRequest("POST", postURL, nil)
	if err != nil {
		log.Fatal(err)
	}

	req.PostForm = *postForm
	err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}
```
all other fields should be pretty straightforward to convert

**Comment by tsidei** [comment]
#269 adds a struct and function to extract route forward payload
