### ISSUE TITLE
Need help to create a missing endpoint in the client go vs mailgun api

### ISSUE THREAD

**Issue by piclemx** [mailgun/mailgun-go#118]
I'm writing a prometheus exporter for our bounce at my job. I was looking to used the mailgun golang client but like i saw in the code. Nothing is done for 

```
GET /<domain>/stats/total
```

https://documentation.mailgun.com/en/latest/api-stats.html#stats

Anyone can help to complete this one or tells me you already have work done for this?

**Comment by pirogoeth** [comment]
@piclemx I've added documentation for the `GetStats` method -- both `GET /<domain>/stats` and `GET /<domain>/stats/total` are implemented here: https://github.com/mailgun/mailgun-go/blob/master/stats.go#L79
