### ISSUE TITLE
[Question] How do I "ping" the client to check the setup is successful before doing further calls?

### ISSUE THREAD

**Issue by jfragosoperez** [mailgun/mailgun-go#125]
When writing Golang code it's usual that an object initializer (New function) returns an object or an error if any defined preconditions for the instance generation fail.

I was wondering if is there any "Sanity Check" call (the usual ping when connecting to a DB or service) to check everything is set up properly and the service is available, before doing any further calls. 

A little bit of the scope I'm running: I'm setting up different kind of mailing workers, and I want to have an iniatializer on the top, to ensure that for instance, all the servers have the proper envvars defined when initializing the client, if they're empty for example, or wrong, I want to panic. (it makes no sense to me, in my case to try sending a message and see it failing after due to an unproper config.)

I wait for your news. Many thanks

**Comment by thrawn01** [comment]
There is no way to ping an HTTP server. You can hit one of the endpoints and see if it responds. If you can come up with a reasonable solution make a PR and I'll merge it.

**Comment by jfragosoperez** [comment]
I was thinking about adding a call to a health endpoint, but I guess there is none. Another solution could be calling a simple and fast endpoint which requires all the env params (was thinking about ips call, but it only involves the apiKey). The mailgun docs don't reflect any health endpoint, but it could be done a previous call like this one: 

https://api:{api_key_val}@api.mailgun.net/v3/domains/{name_of_provided_domain}

what do you think?

**Comment by jfragosoperez** [comment]
which is BTW a call to GetSingleDomain() so problem solved, I'll go for it.

This will test the whole env. before going further.
