### ISSUE TITLE
TimestampNano giving wrong timestamp when rendering JSON

### ISSUE THREAD

**Issue by miloskrca** [mailgun/mailgun-go#136]
The MarshalJSON method on TimestampNano is adding Nanoseconds to seconds which is giving strange values.

E.g. for 1533922516.538978 (08/10/2018 @ 5:35pm (UTC)) MarshalJSON is giving 2072900564, which is 09/08/2035 @ 9:42pm (UTC)

**Comment by thrawn01** [comment]
I think this is fixed in the V3 branch #149 I've added a test providing the example `1533922516.538978`

**Comment by thrawn01** [comment]
Merged into v3 Release
