### ISSUE TITLE
Empty json response with empty credentials.

### ISSUE THREAD

**Issue by eloyucu** [mailgun/mailgun-go#138]
Hi everyone.

I think you have a litle issue when the Mailgun "object" is created with empty params.  Like this:
```
Mailer = mailgun.NewMailgun("", "", "")
```
The problem is that the response is an empty json object `{}`, so when the code of `Send` function arrives here:
```
var response sendMessageResponse
err = postResponseFromJSON(r, payload, &response)
if err == nil {
	mes = response.Message
	id = response.Id
}
```
It generates this error: `invalid character 'M' looking for beginning of value` It would be great to use something more verbose, something like: "Your credentials/domain are incorrect."

Thanks.

**Comment by SpareShade** [comment]
This still returns the same payload ...
