### ISSUE TITLE
MailboxVerification parsing error

### ISSUE THREAD

**Issue by mlesar** [mailgun/mailgun-go#140]
Per [documentation](https://documentation.mailgun.com/en/latest/api-email-validation.html#example) this parameter can be: `true`, `false`, `unknown` or `null`
Currently we are getting errors like (`master` branch):
`json: invalid use of ,string struct tag, trying to unmarshal "unknown" into bool`

And the response is:
```
{
    "address": "some_email@aol.com",
    "did_you_mean": null,
    "is_disposable_address": false,
    "is_role_address": false,
    "is_valid": true,
    "mailbox_verification": "unknown",
    "parts":
    {
        "display_name": null,
        "domain": "aol.com",
        "local_part": "some_email"
    },
    "reason": null
}
```

**Comment by thrawn01** [comment]
Thank you for reporting this.
