### ISSUE TITLE
VerifyWebhookRequest always return false

### ISSUE THREAD

**Issue by vincent-lhote** [mailgun/mailgun-go#143]
I used the method in this package and it always return false, including from the mailgun webhook tests.

I believe the calls to req.FormValue(xxx) are the problem, it returns empty for all values.
https://github.com/mailgun/mailgun-go/blob/4071f66f00fb74b08ae720f28ee9fcd98ebfd69e/webhooks.go#L82
https://github.com/mailgun/mailgun-go/blob/4071f66f00fb74b08ae720f28ee9fcd98ebfd69e/webhooks.go#L83
https://github.com/mailgun/mailgun-go/blob/4071f66f00fb74b08ae720f28ee9fcd98ebfd69e/webhooks.go#L86

**Comment by thrawn01** [comment]
Unable to replicate this issue locally.

**Comment by thrawn01** [comment]
@vincent-lhote I've setup my own webhook and identified the issue. Looks like this hasn't worked properly for some time. I'm putting together a patch now.

**Comment by thrawn01** [comment]
@vincent-lhote Thanks for reporting this issue! Looks like the `VerifyWebhookRequest()` was for the older webhook 1.0 API. I've added support for webhooks 2.0 which is what new customers get by default. 

Take a look at #151  I've added documentation on how to verify the signature and parse the events provided in the webhook payload.

**Comment by thrawn01** [comment]
Merged into master and tagged as v3.2.0
