### ISSUE TITLE
When is v2 released

### ISSUE THREAD

**Issue by chiptus** [mailgun/mailgun-go#144]
Hey, thanks for a great library. It definitely makes it easier to use mailgun.

I've seen that the main branch is for v2 release canditate and I prefer to use the new version over v1. Do you have an estimation on when it's going to be released? Is there anything I can help with?

thanks!

**Comment by thrawn01** [comment]
V2 has been merged into master but I never tagged a v2.0 release! There is now a shiny new v2.0.0 tag

**Comment by chiptus** [comment]
Thanks!
