### ISSUE TITLE
Allow users to pass in `nil` for `context.Context`

### ISSUE THREAD

**Issue by thrawn01** [mailgun/mailgun-go#150]
If the user provides `nil` apply a default timeout to all network operations

**Comment by mbanzon** [comment]
Is this necessary? I can't remember what the standard library do but it would be good to lean on their approach.

I'm thinking that both `nil` and `context.TODO()` would require code changes.

Am I missing something?

**Comment by thrawn01** [comment]
Didn't know about `context.TODO()`

https://www.programming-books.io/essential/go/d5224e27ff724a33a79cb4e03a5eb333-context.todo-vs.context.background

Looks like `context.TODO()` is the right way to go about this, if someone doesn't want a context, they can pass in `Background()` or `TODO()`. I can close this.
