### ISSUE TITLE
go get package fails

### ISSUE THREAD

**Issue by shaumux** [mailgun/mailgun-go#152]
> go get github.com/mailgun/mailgun-go/v3/

> package github.com/mailgun/mailgun-go/v3: cannot find package "github.com/mailgun/mailgun-go/v3" in any of:
>         /usr/lib/go/src/github.com/mailgun/mailgun-go/v3 (from $GOROOT)
>         /home/shaumux/belong/go/mercury/src/github.com/mailgun/mailgun-go/v3 (from $GOPATH)

> go env

> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/shaumux/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/home/shaumux/belong/go/mercury"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/lib/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build459313934=/tmp/go-build -gno-record-gcc-switches"

This causes the whole thing to fail with dep as it searches for even sub package inside v3/ subpackage

**Comment by mbanzon** [comment]
I'm not sure about this, but shouldn't you only use the `/v3`-part of the package name if you are using `go mod`?

Manually `go get`'ing and using `dep` you should stick with `github.com/mailgun/mailgun-go` as the package name afaik.

**Comment by shaumux** [comment]
Yes, but the Readme states
> $ go get github.com/mailgun/mailgun-go/v3
Also the source code has a bunch of imports with the v3 in the path which would fail if I use a plain go get, and try to build a project.

**Comment by mbanzon** [comment]
`go get github.com/mailgun/mailgun-go` works perfectly on my machine.

What version of Go are you using?
As the README states support for Go 1.10 and earlier is not possible from v3 forward.

@thrawn01 should have the details 😏

**Comment by thrawn01** [comment]
I will make a note in the documentation differentiating between those who are using golang modules and those who are not. @mbanzon Perhaps I should just make the examples without the `/v3` at the end until people are ready to migrate to golang modules..

**Comment by mbanzon** [comment]
@thrawn01 imho the default should be Go modules. Using the latest toolchain will give you support - and everyone should be assumed to use the latest. If they are not I think they know themselves.

**Comment by shaumux** [comment]
@mbanzon 
> go get github.com/mailgun/mailgun-go

works fine, my point is the installation instructions are incorrect for go get in the readme
Also, the events.go file in the root has an import 
> "github.com/mailgun/mailgun-go/v3/events"

Now If I were to do plain go get, this would break things wouldn't it?

**Comment by thrawn01** [comment]
@shaumux I understand the confusion. Golang 1.11 has support for a new dependency model called 'modules'. (see https://github.com/golang/go/wiki/Modules) 

Because this library supports golang modules import paths now end in the major version number of the library, in this case `/v3`.  This can be confusing to users that are not using the new golang modules feature. I'll make some notes in the readme to help new users until golang modules is adopted by most golang users.

**Comment by royalgiant** [comment]
I'm running into the same issue. How was this resolved?

**Comment by thrawn01** [comment]
@royalgiant version 3 of mailgun-go uses modules as introduced in golang 1.11 (See https://github.com/golang/go/wiki/Modules). If you are using go 1.11 can you provide some details on what the error is and what you are trying to accomplish. (IE: are you using `dep`?)

**Comment by royalgiant** [comment]
I resolved the issue @thrawn01. For anyone using google app engine. The version they use is 1.9 apparently. So, to fix that, I used dep ensure to lock mailgun to 2.0. That fixed the issue.

**Comment by CyberCatfish** [comment]
I also created a GAE / Go 1.9 in a new environment, and the same problem occurred.
There is no problem in the old environment, but I would like to move to the new environment if possible.
What should I do?

> $ goenv global 1.9.4
> $ go get github.com/mailgun/mailgun-go
> $ goapp serve sample
> ...
> ERROR    2019-03-18 03:13:27,031 instance_factory.py:243] Failed to build Go application: (Executed command: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/goroot-1.9/bin/go-app-builder -app_base ~/Go/nack5-touch3 -api_version go1 -arch 6 -dynamic -goroot /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/goroot-1.9 -nobuild_files ^^$ -incremental_rebuild -unsafe -binary_name _go_app -extra_imports appengine_internal/init -work_dir /var/folders/8x/zflyr_4s0x32lctg6r6brq240000gn/T/tmpZ_cqliappengine-go-bin -gcflags -I,/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/goroot-1.9/pkg/darwin_amd64_appengine -ldflags -L,/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/goroot-1.9/pkg/darwin_amd64_appengine main.go)
> ~/GoLib/src/github.com/mailgun/mailgun-go/events.go:8:2: can't find import: "github.com/mailgun/mailgun-go/v3/events"
> 2019/03/18 12:13:25 Can't find package "github.com/mailgun/mailgun-go/v3/events" in $GOPATH: cannot find package "github.com/mailgun/mailgun-go/v3/events" in any of:
> 	/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine/goroot-1.9/src/github.com/mailgun/mailgun-go/v3/events (from $GOROOT)
> 	~/GoLib/src/github.com/mailgun/mailgun-go/v3/events (from $GOPATH)

**Comment by simhalending** [comment]
Seem to get this same issue on App Engine with Go runtime 1.12. Am not using mods.

Works fine locally, but cannot deploy to App Engine.

`2019/11/05 09:01:54 staging for go1.12
2019/11/05 09:01:54 GO111MODULE=auto, but no go.mod found, so building with dependencies from GOPATH
main-package: joeblogs.io/play/test001
2019/11/05 09:01:54 Staging second-gen Standard app (GOPATH mode): failed analyzing /Users/joeblogs/go/src/joeblogs.io/play/test001: cannot find package "github.com/mailgun/mailgun-go/v3/events" in any of:
	($GOROOT not set)
	/Users/joeblogs/go/src/github.com/mailgun/mailgun-go/v3/events (from $GOPATH)
GOPATH: /Users/joeblogs/go`

**Comment by bmrfvr** [comment]
@simhalending Did you ever get this figured out?

**Comment by simhalending** [comment]
@bmrfvr Nope - ended up just looking into another service.

**Comment by germolinal** [comment]
So, after a lot of learning and testing, I got into this same issue. Is there any tutorial/example that shows how to do this? I really don't want to migrate to other services.

I am using app engine with go 1.13 ... I could not set this up with modules and without them, it does not work.
