### ISSUE TITLE
Create Domain ignores response

### ISSUE THREAD

**Issue by shaumux** [mailgun/mailgun-go#154]
The current implementation seems to ignore the repsonse from a CreateDomain call, returning only the error, is there a particular reason for doing it this way?

From what I understand the send records, and receive records returned would be needed to added to the nameserver, hence with the current implementation would require another call using the GetDomain.

**Comment by thrawn01** [comment]
Take a look at the PR, I think this would be an improvement.

**Comment by shaumux** [comment]
The changes look good, this would, the DomainResponse should help with unifying the domain repsonses
