### ISSUE TITLE
smtp_password in CreateDomain should be optional

### ISSUE THREAD

**Issue by shaumux** [mailgun/mailgun-go#159]
Any reason to make the smtp_password a required parameter? Since it seems to be optional in the API.
Sould it be moved to CreateDomain struct?

**Comment by thrawn01** [comment]
Just tested this and smtp_password is indeed optional. Documentation on https://documentation.mailgun.com/en/latest/api-domains.html#domains also needs to be updated. The parameter is not marked as optional.

**Comment by thrawn01** [comment]
See #184
