### ISSUE TITLE
Empty Route Description stored as Bool

### ISSUE THREAD

**Issue by NicoleYson** [mailgun/mailgun-go#161]
The Routes struct expects the route description to be a string https://github.com/mailgun/mailgun-go/blob/96b77793a39dde24458e6c780a9defdadae410a9/routes.go#L18 

However if the description is empty, it stores it as a boolean resulting in this error when getting routes:
```
panic: json: cannot unmarshal bool into Go struct field Route.description of type string 
``` 

Can this be fixed? 
Possibly by having it stored as an empty string instead of a boolean?

**Comment by thrawn01** [comment]
@NicoleYson Thank you for reporting this. I've identified the issue in the Mailgun API `/routes` code and have a fix. Once the change is approved and deployed to our servers mailgun-go should be able to unmarshal the JSON properly.

**Comment by NicoleYson** [comment]
It appears to be working! 
Thanks @thrawn01! I really appreciate it 😄
