### ISSUE TITLE
CreateDomain documentation doesn't seem right

### ISSUE THREAD

**Issue by mbanzon** [mailgun/mailgun-go#167]
The in-source documentation show a lot of parameters that seem to have been moved to the settings struct. The SMTP password parameter could also be moved to the struct - but I guess this would trigger a major version change (?).

cc @thrawn01

**Comment by thrawn01** [comment]
Yes, Which is why I've not done it yet. It's not a huge problem as the password can be empty. It just probably shouldn't be in the signature of function.

**Comment by thrawn01** [comment]
See #184
