### ISSUE TITLE
Sending and retrieving user variables

### ISSUE THREAD

**Issue by mfridman** [mailgun/mailgun-go#173]
We use the go client to send emails and retrieve events.

For outgoing emails we attach metadata for each recipient with `AddRecipientAndVariables`, and then add email metadata with `AddVariable`.

In both `message.recipientVariables` and `message.variables` we observe the correct metadata. We then call `Send` .. which parses out the pieces correctly.

https://github.com/mailgun/mailgun-go/blob/master/messages.go#L528

---

Sometime in the future we invoke the client and `ListEvents` with `Event`, from `UserVariables` we get back the email metadata:

specifically: 
```
UserVariables map[string]interface{} `json:"user-variables"
````

So the question is how to also get back the individual recipient metadata from events?

**Comment by thrawn01** [comment]
Mailgun has 2 different ways to attach variables. See https://documentation.mailgun.com/en/latest/user_manual.html#sending-via-smtp and search for 'variables'.

I believe `user-variables` returned in events will only return `X-Mailgun-Variables` but not `X-Mailgun-Recipient-Variables`. If you have other questions I would contact mailgun support, they would be able to help you.

**Comment by Cl2rk3Gr1ff1n** [comment]
@thrawn01 How to get the **X-Mailgun-Recipient-Variables** in events?
