### ISSUE TITLE
Using email templateExample.html files as template stored locally or on server

### ISSUE THREAD

**Issue by DanielSpring** [mailgun/mailgun-go#174]
Hi,

I'm new to Mailgun and Go, I was just wondering if anyone can point me in the right direction. I've come accross some examples such as https://www.mailgun.com/blog/delivering-html-emails-mailgun-go. I've managed to use SendWithUs and use their templates as they us template id's, however, I want to use a html file which contains CSS as a template, stored locally or on a server somewhere. Is there any simpler examples than the one above?

Thanks

**Comment by thrawn01** [comment]
Mailgun support might be able to assist. I'm not sure exactly what you are asking for, the blog post gives an example of using an HTML/CSS template stored locally. You can use the new template API, but the golang documentation is not complete and I've not tested it yet. 

https://documentation.mailgun.com/en/latest/user_manual.html#templating

**Comment by thrawn01** [comment]
Leaving this here as a TODO

* Complete the mailgun documentation for sending templates with mailgun-go
* Test sending email with templates and variables.

**Comment by thrawn01** [comment]
See #184
