### ISSUE TITLE
Expose code in DeliveryStatus

### ISSUE THREAD

**Issue by mfridman** [mailgun/mailgun-go#175]
Is this waiting for a fix in the mailgun API?

https://github.com/mailgun/mailgun-go/blob/b42eaacf2c5e3c44923a7c1b2479535508738170/events/objects.go#L75

**Comment by mfridman** [comment]
Maybe expose it as an `interface{}` with a comment? Not ideal, but does enable the consumer to do the assertion for the various types as a best effort.

**Comment by thrawn01** [comment]
@mfridman Thanks for bringing this up. I've double checked and it does appear this was a VERY old comment and the issue with `Code` type has been resolved.
