### ISSUE TITLE
Missing UserVariables in many of the data types

### ISSUE THREAD

**Issue by mfridman** [mailgun/mailgun-go#176]
Based on the latest API docs, the Event API returns `user-variables` in many (if not all) the event types.

```
UserVariables map[string]string `json:"user-variables"`
```

https://documentation.mailgun.com/en/latest/api-events.html#event-structure

Currently the `/v3` client only exposes `UserVariables` in opened, unsubscribed and clicked.

---

imo these "user-variables" should be stored in the `Message` struct, as they are specific to the message itself and less to the event type.

**Comment by thrawn01** [comment]
@mfridman Thanks for reporting this, I checked and all the Message events do all have `user-variables`. I've added the field to each event.
