### ISSUE TITLE
Expose Description field in DeliveryStatus

### ISSUE THREAD

**Issue by mfridman** [mailgun/mailgun-go#178]
In the latest docs, there is a description field which has some useful info (that's not available in message).

Consider adding `Description` field to the `DeliveryStatus` struct. 

https://documentation.mailgun.com/en/latest/api-events.html#event-structure

### Failed (Permanent):

```
"delivery-status": {
    "attempt-no": 1,
    "message": "",
    "code": 605,
    "description": "Not delivering to previously bounced address",
    "session-seconds": 0.0
},
```

vs 

### Failed (Permanent, Delayed Bounce):

```
"delivery-status": {
    "message": "smtp; 550-5.1.1 The email account that you tried to reach does not exist.",
    "code": "5.1.1",
    "description": ""
},
```

**Comment by thrawn01** [comment]
@mfridman Thanks for reporting, let me know if you find anything else that should be added before I merge the PR.

**Comment by mfridman** [comment]
@thrawn01 noticed 2 other issues, but unrelated to missing fields, more so expected values aren't coming back (maybe an issues parsing somewhere). Want me to open a separate ticket ?

(I confirmed the values are there by hitting the `/events?message-id=` endpoint manually)

**Comment by thrawn01** [comment]
Go for it!
