### ISSUE TITLE
Missing values for certain event types

### ISSUE THREAD

**Issue by mfridman** [mailgun/mailgun-go#180]
1. `accepted` and `delivered` events return empty values for:

```
UserVariables  map[string]string `json:"user-variables"``
```

I checked the raw output and got `UserVariables:map[]` from the go-client, maybe unmarshalling issue?

- this doesn't happen for `opened` or `clicked` events (not sure about others)
- I validated the API is actually sending back those values by hitting the endpoint directly `/events?message-id=` , happy to provide details offline.

![Screen_Shot_2019-03-29_at_4_58_22_PM](https://user-images.githubusercontent.com/6278244/55262412-111edd80-5244-11e9-82ae-476d1b1bf148.png)

---

2. the `smtp_code` is never returned through the client (for any event type). Confirmed the API is indeed returning a valid code, in the case above it was..

![Screen_Shot_2019-03-29_at_5_02_25_PM](https://user-images.githubusercontent.com/6278244/55262684-eed98f80-5244-11e9-965a-35c3c4a468ab.png)

**Comment by thrawn01** [comment]
@mfridman EasyJSON files should have been regenerated after adding the fields. I've done this and will merge and bump the version. See #179

**Comment by mfridman** [comment]
@thrawn01 Thanks. I'll wait for the newer version, `v3.3.3`, and give it another go.

**Comment by thrawn01** [comment]
@mfridman https://github.com/mailgun/mailgun-go/releases/tag/v3.3.3

**Comment by mfridman** [comment]
@thrawn01 Thanks, lgtm.
