### ISSUE TITLE
go get issue for github.com/mailgun/mailgun-go/v3

### ISSUE THREAD

**Issue by DMEvanCT** [mailgun/mailgun-go#181]
go get github.com/mailgun/mailgun-go/v3
package github.com/mailgun/mailgun-go/v3: cannot find package "github.com/mailgun/mailgun-go/v3" in any of:
        /usr/local/go/src/github.com/mailgun/mailgun-go/v3 (from $GOROOT)
        /Users/ehaston/go/src/github.com/mailgun/mailgun-go/v3 (from $GOPATH)

Seems to be an issue when I install with glide too.

**Comment by thrawn01** [comment]
Please See
https://github.com/mailgun/mailgun-go/issues/152#issuecomment-456882019

This is also mentioned in the README. We have had a few issues around this, feedback on how we can make this clear and avoid confusion is welcome.
