### ISSUE TITLE
DeliveryStatus expects upstream smtp code to be int (not string)

### ISSUE THREAD

**Issue by mfridman** [mailgun/mailgun-go#186]
Follow up to see if you spotted the problem on the backend events API.

@thrawn01 We got a bunch of information that may help debug this, it specifically happened with `failed` event type. Below is one example, but we noticed this for hundreds of events.

The short-lived ID is real, so you can look it up in your backend, anything PII is redacted:

```json
{
    "severity": "permanent",
    "timestamp": 1555608660.216357,
    "delivery-status": {
        "message": "smtp; 550 5.1.1 <email@example.com>... User    unknown",
        "code": "5.1.1",
        "description": ""
    },
    "log-level": "error",
    "id": "sH4BzzWYTA-hAPIvEkLmpg",
    "reason": "bounce",
    "flags": {
        "is-delayed-bounce": true
    },
    "recipient": "email@example.com",
    "event": "failed"
}
```

_Originally posted by @mfridman in https://github.com/mailgun/mailgun-go/pull/182#issuecomment-485002639_

**Comment by thrawn01** [comment]
@mfridman I have a fix ready which should be deployed tomorrow. Once it goes live new failed delayed-bounce events will have the SMTP `550` code and not the DSN code. (5.1.1)

**Comment by thrawn01** [comment]
@mfridman This change should now be live on the mailgun API. Please advise if you see any codes that return a string instead of an integer.

**Comment by mfridman** [comment]
@thrawn01 Thanks for following up. I wish all backend APIs were written in a strongly-typed language. I.e., it should not be possible to return a string "5.1.1" where an int is expected.

Unfortunately we're still seeing the issue, latest one was:

> May 6, 2019 12:46:19 PM EDT

This time it's for failed events of severity permanent with `"code": "5.1.10"` 

`ts: 1557160852.631647` and short lived id "vISg5TvuTvmwQzbYMevzLA" might help you locate those in the backend API

**Comment by thrawn01** [comment]
@mfridman Thank you for providing the timestamp, made it super simple to find your event. Looks like that last event was emitted before the change was deployed. Change was deployed on 05/06/2019 at 18:40:00 UTC. You shouldn't be seeing any more 5.1.0 codes. 

Let me know if you do.

**Comment by mfridman** [comment]
Thanks, we haven't seen anymore failed events after May 6, 2019 12:46:19 PM EDT

Early next week we'll switch back to the upstream client. 

(we forked it and made modifications that triggered alerts whenever this happens, but we obviously don't want that)

**Comment by mfridman** [comment]
@thrawn01 Going to close the issue. 

If it happens again we might want to consider changing `delivery-status.code` from `int` to `interface{}`. Then allow the end-user to type switch on the field?
