### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by DMEvanCT** [mailgun/mailgun-go#190]
Is it possible to add documents for sending email via template?

**Comment by thrawn01** [comment]
I don't understand the question, Are you asking about file attachments? Questions not directly related to mailgun-go should be asked through the mailgun support system. They actually know more about the API and sending details than I do.  https://www.mailgun.com/contact/support

**Comment by DMEvanCT** [comment]
No it's in relation to using a template from created in the web console when sending email.
