### ISSUE TITLE
mailgun.go looks have no Interface `UpdateDomainTracking`

### ISSUE THREAD

**Issue by saitotqr** [mailgun/mailgun-go#192]
mailgun.go looks have no Interface `UpdateDomainTracking` .
I'm trying to import/export mailgun settings to JSON, But I have no way to update `DomainTracking` settings to domain which I created.

**Comment by thrawn01** [comment]
@saitotqr Try release candidate 3.6.0-rc.1 If this works for you I'll tag a full release.
