### ISSUE TITLE
Mailgun interface is missing VerifyWebhookSignature

### ISSUE THREAD

**Issue by tv42** [mailgun/mailgun-go#202]
MailgunImpl has VerifyWebhookSignature (https://godoc.org/github.com/mailgun/mailgun-go#MailgunImpl.VerifyWebhookSignature) but it's not present in the interface Mailgun. If you are going to provide such an all-the-things interface, it should also be kept up to date ;)

**Comment by thrawn01** [comment]
Fixed in release 3.6.1
