### ISSUE TITLE
Add SetVersion method to Message to specify which template version to use.

### ISSUE THREAD

**Issue by jrhdoty** [mailgun/mailgun-go#208]
It looks like there is no way to specify the specific version of a template to associate with a message in the golang API, so it defaults to the current active template. The option to specify a version is listed in the docs for the Mailgun Sending API:

> [t:version | Use this parameter to send a message to specific version of a template](https://documentation.mailgun.com/en/latest/api-sending.html#sending)

This would be useful for A/B testing, using environment specific versions for dev, prod etc.

**Comment by thrawn01** [comment]
I think the linked PR covers this case now, closing.
