### ISSUE TITLE
MIME/Quickview only displaying Template Name

### ISSUE THREAD

**Issue by liveyourheart** [mailgun/mailgun-go#216]
Using the code below, I am sending emails to mailgun successfully, however the quickview and MIME are both just set as the provided template name.  I attempted adding variables using both `AddTemplateVariable` and `AddVariable` as mailgun support suggested that the message content was found within the user variables.  Is there something I'm missing?

![image](https://user-images.githubusercontent.com/9070786/78822131-29215500-79a0-11ea-848b-6051269c34da.png)

```
func (s *MailgunService) Notify(n data.MailgunNotification) error {
	if n.TemplateID == "" {
		log.Printf("error sending email, no Template ID provided: %v", n)
		return nil
	}
	subject := "test subject"
	message := s.Client.NewMessage("", subject, "", n.EmailAddress)

	message.SetTemplate(n.TemplateID)
	message.SetTracking(true)
	message.SetReplyTo(n.ReplyTo)
	for k, v := range n.Variables {
		if vErr := message.AddVariable(k, v); vErr != nil {
			log.Printf("error adding variable: %v", vErr)
		}

		if tvErr := message.AddTemplateVariable(k, v); tvErr != nil {
			log.Printf("error adding template variable: %v", tvErr)
		}
	}
	aErr := message.AddTemplateVariable("attachments", n.Attachments)
	if aErr != nil {
		log.Printf("error adding attachments: %v", aErr)
	}

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*30)
	defer cancel()
	if _, _, err := s.Client.Send(ctx, message); err != nil {
		return fmt.Errorf("error sending email: %v", err)
	}

	return nil
}

```

**Comment by thrawn01** [comment]
Hi @liveyourheart I'm not following what you are trying todo, but when I'm having trouble understanding what the library is doing. I enable debug so I can see exactly what API calls are made. mailgun-go will log a curl command if you do the following before you set `mailgun.Debug = true` before creating a new instance.

```go
mailgun.Debug = true
mg, err := mailgun.NewMailgunFromEnv()
```
I hope this helps you figure out your problem.

**Comment by liveyourheart** [comment]
I followed up with mailgun support and it turns out that the issue was actually a misunderstanding in how the template quick view was supposed to display.  thanks for your help 👍
