### ISSUE TITLE
Failed unmarshall EmailVerification struct

### ISSUE THREAD

**Issue by riskimidiw** [mailgun/mailgun-go#217]
https://documentation.mailgun.com/en/latest/api-email-validation.html#example

based on this documentation, reason in validation response is array of string, but reason type in EmailVerification struct is string, so we cannot unmarshall it. we need to update EmailVerification struct to the latest of email validation response
```
json: cannot unmarshal array into Go struct field EmailVerification.reason of type string
```
- golang version: 1.14.1
- mailgun-go version: 4.0.1

**Comment by thrawn01** [comment]
Thanks for reporting this!
