### ISSUE TITLE
Docs bug: since sending an html formatted email is a common task please document that

### ISSUE THREAD

**Issue by ORESoftware** [mailgun/mailgun-go#219]
Since sending an html formatted email is a common task can this please be added to the docs (the readme file)?  When I search for "html" it doesn't appear in the readme at all.

**Comment by RichardLindhout** [comment]
I agree with you it should be documented, I was looking for it too. 

Found something inside of the test which looks like its what we want!

```golang
	m := mg.NewMessage(
		"Excited User <YOU@YOUR_DOMAIN_NAME>",
		"Hello",
		"Testing some Mailgun awesomeness!",
		"foo@example.com",
	)
	m.AddCC("baz@example.com")
	m.AddBCC("bar@example.com")
	m.SetHtml("<html>HTML version of the body</html>")
	m.AddAttachment("files/test.jpg")
	m.AddAttachment("files/test.txt")

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*30)
	defer cancel()

	_, id, err := mg.Send(ctx, m)
```

**Comment by RichardLindhout** [comment]
"Testing some Mailgun awesomeness!" is the summary of email clients see. It's not in the content.

**Comment by kelub** [comment]
> I agree with you it should be documented, I was looking for it too.
> 
> Found something inside of the test which looks like its what we want!
> 
> ```go
> 	m := mg.NewMessage(
> 		"Excited User <YOU@YOUR_DOMAIN_NAME>",
> 		"Hello",
> 		"Testing some Mailgun awesomeness!",
> 		"foo@example.com",
> 	)
> 	m.AddCC("baz@example.com")
> 	m.AddBCC("bar@example.com")
> 	m.SetHtml("<html>HTML version of the body</html>")
> 	m.AddAttachment("files/test.jpg")
> 	m.AddAttachment("files/test.txt")
> 
> 	ctx, cancel := context.WithTimeout(context.Background(), time.Second*30)
> 	defer cancel()
> 
> 	_, id, err := mg.Send(ctx, m)
> ```

it work

**Comment by RichardLindhout** [comment]
Yeah I use it too, works perfect and fast! :)

**Comment by thrawn01** [comment]
Just remembered I wrote a blog post about this. https://www.mailgun.com/blog/delivering-html-emails-mailgun-go
