### ISSUE TITLE
Webhook example in README cannot decode JSON

### ISSUE THREAD

**Issue by zt9** [mailgun/mailgun-go#221]
When I have a route set to forward to a url, the [example here](https://github.com/mailgun/mailgun-go#webhook-handling) does not work because the code expects to decode JSON, but the post from mailgun is x-www-form-urlencoded

I get the following error message

`decode JSON error: invalid character 'r' looking for beginning of value`

I have the following route

```
match_recipient(".*@a.mysiute.com") Priority: 0
forward("https://jfk233.ngrok.io/mailgun/incoming/")
stop()
```

I am using:

```
go version go1.12.4 darwin/amd64
mailgun-go Release v4.1.0
```

**Comment by thrawn01** [comment]
The [example webhook](https://github.com/mailgun/mailgun-go#webhook-handling) is for receiving [events via webhook](https://documentation.mailgun.com/en/latest/api-webhooks.html?highlight=webhook#webhooks)

The route example you posted does not send events, but the content of the email that was received. [See Routes Documentation](https://documentation.mailgun.com/en/latest/api-routes.html?highlight=webhook#routes)
