### ISSUE TITLE
Allow to set initial template Version

### ISSUE THREAD

**Issue by danieldias51** [mailgun/mailgun-go#222]
Hi, 

When creating a new [template](https://github.com/mailgun/mailgun-go/blob/master/template.go#L36) even if we specificy the inital tag it's ignored,
The  CreateTemplate method doesn't copy the tag value to the request payload even though the [documentation](https://documentation.mailgun.com/en/latest/api-templates.html#store-new-template) says we can set an initial template tag.

**Comment by thrawn01** [comment]
Released v4.1.1
