### ISSUE TITLE
how to cancel send delivery time ?

### ISSUE THREAD

**Issue by harmnot** [mailgun/mailgun-go#227]
is is possible to cancel mail that have scheduled ? any documentation for this ? I have read [this doc](https://documentation.mailgun.com/en/latest/user_manual.html?highlight=batch%20sending#introduction) any idea or example?

**Comment by thrawn01** [comment]
You will have to contact mailgun support if you want to cancel a scheduled mail. I don't know of any API's we provide publicly to cancel a scheduled mail.
