### ISSUE TITLE
Bulk upload Unsubscribes is not implemented

### ISSUE THREAD

**Issue by paulhowardflanders** [mailgun/mailgun-go#233]
Per the [Mailgun documentation](https://documentation.mailgun.com/en/latest/api-suppressions.html#add-multiple-unsubscribes), the Mailgun API supports uploading up to 1000 unsubscribes at once but this is not implemented yet in mailgun-go. Is there a plan to implement this in the near future? I am happy to open a PR for it as long as it will be reviewed 🙂

**Comment by thrawn01** [comment]
PRs are always welcome! How fast I respond to a PR creation depends on my current work load. I've only turned away 1 PR since I began working on this repo.
