### ISSUE TITLE
Need to regenerate easyjson following recent Event changes

### ISSUE THREAD

**Issue by martinhpedersen** [mailgun/mailgun-go#235]
Commit 399d92b0a5e3dc749c0fe10643e6c54e637ed1ad added Storage to Accepted,Delivered and Failed events, but easyjson was not regenerated to reflect the changes. The result is empty Storage value for those events.

I can provide a PR if needed.

Thanks!

**Comment by thrawn01** [comment]
Thank you for reporting this, It happens far too often! We should be using json-iterator anyway. I've created a PR for this. Let me know if this solves you problem.

**Comment by martinhpedersen** [comment]
Thanks! The PR #236 seems to fix this issue 👍
