### ISSUE TITLE
HTML Formatted Email with href Doesn't Work

### ISSUE THREAD

**Issue by tinakurian** [mailgun/mailgun-go#237]
I am sending an HTML formatted email very similar to how it is done here: https://github.com/mailgun/mailgun-go/issues/219#issuecomment-636322783 

However, the problem that I'm seeing is that the URL cannot be clicked in the email. I've compared the source of the email to another email that does have a working link and the only difference I can see is that the Content-Type and the Content-Transfer-Encoding were different.

**The working href email source had the following:**
```
Content-Transfer-Encoding: 7bit
Content-Type: text/html; charset="ascii"
```

**The broken href email source had the following:** 
```
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset="utf-8"
```

**What I've tried**
I've attempted to use AddHeaders() to set this, however, the source does not contain the headers. 

I have also tried using NewMIMEMessage similar to the example found here: https://github.com/mailgun/mailgun-go/blob/4549b26cb022921a04c55f8793e60b420587746d/examples_test.go#L100-L121

However, it looks like the Content-Type and the Content-Transfer-Encoding are appended to the body of the email. 

How can I send an email containing an HTML body with working href links?

**Comment by thrawn01** [comment]
Hi @tinakurian, Sounds like the MIME you are submitting might be incorrect, or you have link re-writing (a mailgun feature) and there is some issue with how mailgun is re-writing your emails. You should open a support ticket and support can look at the actual content of your message to hopefully help you diagnose.  I suggest making sure link re-writting is off for your domain and and try your send again. If you submit MIME without link re-write on mailgun shouldn't modify or "append" any transfer encodings to the MIME. 

Hope that helps.
