### ISSUE TITLE
How to send LinkedResources?

### ISSUE THREAD

**Issue by tpoxa** [mailgun/mailgun-go#239]
I am trying to find a robust way to send emails with images in it.
I've found that inline attachment (cid) does not work OK for every user, even within gmail.

I found this solution  https://stackoverflow.com/a/32846686 but I was unable to find any mention of LinkedResource within this library.
So question how to do that, or something else to solve my problem.
Thanks.

**Comment by thrawn01** [comment]
You must attach the image as an `inline` then the image can be referenced in the HTML. 

An example is here https://github.com/thrawn01/channel-stats/blob/master/mailgun.go#L64
Full explanation is in this blog post https://www.mailgun.com/blog/delivering-html-emails-mailgun-go
