### ISSUE TITLE
App Engine support

### ISSUE THREAD

**Issue by ohler** [mailgun/mailgun-go#24]
mailgun-go depends on simplehttp, whose App Engine support is unfortunately broken: https://github.com/mbanzon/simplehttp/issues/7

So mailgun-go isn't currently suitable for use on App Engine.

**Comment by karalabe** [comment]
It does have quite a number of compilation errors :P Many places you used `m.client` to access the client, but the function context is actually called `mg`.

E.g. https://github.com/mailgun/mailgun-go/blob/custom-client/credentials.go#L22

**Comment by mbanzon** [comment]
Oh my. I have no idea why that even compiled on my machine!

Thank you for the comment + PR.

**Comment by shawnps** [comment]
+!

**Comment by warent** [comment]
Why did this get closed? :(
Is app engine not going to be supported?

**Comment by warent** [comment]
Oh I see, it looks like SetClient was ultimately added to master branch. Spoke too soon, sorry for the noise! Thanks :D
