### ISSUE TITLE
Make fields public in struct `mailgun.Message`.

### ISSUE THREAD

**Issue by olegburov** [mailgun/mailgun-go#253]
Can you please make fields public in the struct `mailgun.Message` to make it easier for mocking and testing? It's similar to https://github.com/mailgun/mailgun-go/issues/68#issuecomment-313916237.

**Comment by thrawn01** [comment]
I do not understand this request, making internal fields public for the sake of mocks breaks encapsulation. You should mock `mailgun.Message` with an interface. Can you provide more detail on how you expect?

I do however see the need to make the `mailgun.MockServer` internals public.

**Comment by thrawn01** [comment]
See #255

**Comment by thrawn01** [comment]
Closed due to age
