### ISSUE TITLE
SetDeliveryTime Ignored

### ISSUE THREAD

**Issue by devotoare** [mailgun/mailgun-go#254]
I just sent an email to a list and it immediately sent, even though I had used SetDeliveryTime to schedule it less than 3 days in advance (2 days). I see in the logs the X-Mailgun-Deliver-By is set to the correct time I had chosen so I'm not sure if this is an issue with the Go SDK or with the service itself.

**Comment by thrawn01** [comment]
please open a ticket with support, I've not seen `X-Mailgun-Deliver-By` used with a mailing list, so maybe that is the issue.
