### ISSUE TITLE
Change response for `VerifyDomain` method  from (string, error) to (DomainResponse, error)

### ISSUE THREAD

**Issue by zhunik** [mailgun/mailgun-go#257]
In mailgun [API docs](https://documentation.mailgun.com/en/latest/api-domains.html#domains) 
`PUT /domains/<domain>/verify` have the next description: 
```
Verifies and returns a single domain, including credentials and DNS records.
```
for some reason go implementation decided to change response to only domain state. 

https://github.com/mailgun/mailgun-go/blob/a87d271e01bf098b5bf2a1998ebd910bff873c0d/domains.go#L253

The reason behind this request is not only to be on the same page with the docs, but also to get information about DNS records state, and avoid second call to `GetDomain` method.

**Comment by thrawn01** [comment]
Changing this would require a version bump to V5, Perhaps we can make an alternative method and deprecate the old one? PR's welcome!

**Comment by thrawn01** [comment]
Added new `VerifyAndReturnDomain()` method in https://github.com/mailgun/mailgun-go/releases/tag/v4.5.2
