### ISSUE TITLE
How to convert json stored messages to url.Values

### ISSUE THREAD

**Issue by gustavomassa** [mailgun/mailgun-go#258]
![image](https://user-images.githubusercontent.com/16235598/119905748-33dfd600-bf23-11eb-9f2d-96fefd45e859.png)
Hello, I'm using the API to get stored messages, but the API returns the message in JSON format while the notify uses query string format.
I need to get some messages and re-processes manually, simulating the notify hook, but I need to convert the JSON message to url.Values form. What is the best way to accomplish it?

**Comment by thrawn01** [comment]
When you are notified of a stored message you can pull the message in JSON or MIME format by setting the appropriate `Accept` Header. You can use `GetStoredMessage()` and `GetStoredMessageRaw()` in the library to do this. What you do with the message data is out of scope for this library.
