### ISSUE TITLE
Remove simplehttp dependency

### ISSUE THREAD

**Issue by mbanzon** [mailgun/mailgun-go#29]
This heavily relates to https://github.com/mailgun/mailgun-go/issues/24.

IMHO dependencies to external libraries should be removed if possible. The only reason that `mailgun-go` use `simplehttp` is that I originally wrote both libraries in parallel.

Hiding `simplehttp` and its implementation bring trouble when it is needed to use alternative `http.Client` or `http.Transport` (when writing application for GAE eg.).

**Comment by Zevran** [comment]
:+1:
