### ISSUE TITLE
events.ClientInfo is missing the `bot` field

### ISSUE THREAD

**Issue by gnuletik** [mailgun/mailgun-go#295]
The documentation states that there is a `client-info.bot` field in the open/click events:
https://documentation.mailgun.com/en/latest/user_manual.html#open-and-click-bot-detection

However, the SDK does not have this struct field:
https://github.com/mailgun/mailgun-go/blob/afe6db08188523a62bf2001eb9f408f222ee3e68/events/objects.go#L3-L11

**Comment by teros0** [comment]
You're right, I will add it.

**Comment by teros0** [comment]
Done.
