### ISSUE TITLE
Add 'web_scheme' as a primary attribute to Domain

### ISSUE THREAD

**Issue by Szasza** [mailgun/mailgun-go#301]
**Issue**

In `v4.8.2` the `web_scheme` domain attribute is only supported as a create domain operation's option. As per the documentation however it is a primary attribute of the Domain entity: https://documentation.mailgun.com/en/latest/api-domains.html#domains

Also the current implementation only supports `web_scheme` in case of a domain creation, but not for retrieval or update.

**Desired outcome**

Having `web_scheme` supported as a primary attribute of the Domain entity.

**Comment by Szasza** [comment]
@thrawn01 @teros0  I am happy to work on this one if you are ok with the approach.

**Comment by teros0** [comment]
Sounds like a great addition to me.
@thrawn01 what do you think?

**Comment by thrawn01** [comment]
This would be a great addition!
