### ISSUE TITLE
Set preferred reply method for mailing lists missing

### ISSUE THREAD

**Issue by skynexus** [mailgun/mailgun-go#303]
The Mailgun API offers the ability to set the preferred reply method to [mailing lists](https://documentation.mailgun.com/en/latest/api-mailinglists.html#mailing-lists), but this is [currently missing](https://pkg.go.dev/github.com/mailgun/mailgun-go#List) in the mailgun-go library.

I have implemented a proposed solution in #302

**Comment by teros0** [comment]
Thank you for your contribution.
If you want to, you may also update `examples.go` to reflect these changes.
