### ISSUE TITLE
[Feature Request] Add Send Time Optimization (STO) Feature

### ISSUE THREAD

**Issue by cjyang0117** [mailgun/mailgun-go#305]
Dear @thrawn01  ,

I hope this message finds you well. I wanted to express my interest in adding a new feature to the GitHub repository of Mailgun-Go. Specifically, I would like to propose the addition of Send Time Optimization (STO) functionality.

STO is a Mailgun feature that leverages machine learning to determine the most opportune time to deliver a message to a recipient. By delivering the message right before the recipient typically checks their email, STO aims to increase engagement rates and ultimately improve overall conversions and ROI.

To implement this feature, I suggest introducing a new method called SetSTOPeriod to the Message class. This method would allow users to set the o:deliverytime-optimize-period parameter, as described in the Mailgun API documentation (https://documentation.mailgun.com/en/latest/api-sending.html#sending). According to the specification, this parameter should be a string representing the number of hours in [0-9]+h format, with a minimum of 24h and a maximum of 72h. To ensure compliance with this specification, the implemented code would include necessary checks.

I have already prepared a pull request (https://github.com/mailgun/mailgun-go/pull/304) with the proposed changes. If you find this feature appropriate and valuable for the Mailgun-Go repository, I would be grateful for your review and consideration.

Thank you kindly for your time and attention.

Best regards,
Kevin

**Comment by thrawn01** [comment]
Thank you for pinging me again on this issue, I've merged the PR you made, it is very much appreciated.

**Comment by thrawn01** [comment]
Feature is available in https://github.com/mailgun/mailgun-go/releases/tag/v4.9.0

**Comment by cjyang0117** [comment]
Thank you so much for merging my pull request! I'm grateful for the opportunity to contribute to mailgun-go.
