### ISSUE TITLE
Ability to add multiple webhooks for same events.

### ISSUE THREAD

**Issue by Puneet56** [mailgun/mailgun-go#309]

**Comment by vtopc** [comment]
should be possible based on docs - https://documentation.mailgun.com/docs/mailgun/api-reference/openapi-final/tag/Webhooks/

**Comment by vtopc** [comment]
@Puneet56 use https://pkg.go.dev/github.com/mailgun/mailgun-go/v4#MailgunImpl.CreateWebhook

e.g.:
```
mg.CreateWebhook(ctx, name, []string{"https://example.com/1", "https://example.com/2"})
```
