### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference On GetStoredAttachment 

### ISSUE THREAD

**Issue by behrouz-rfa** [mailgun/mailgun-go#312]
The GetStoredAttachment method can panic if the response is nil.

      \`\`\`go
      // GetStoredAttachment retrieves the raw MIME body of a received e-mail message attachment.
      func (mg *MailgunImpl) GetStoredAttachment(ctx context.Context, url string) ([]byte, error) {
        // ...
        response, err := makeGetRequest(ctx, r)
        return response.Data, err // <- this panics if response is nil
      }
      \`\`\`

      It should check if the response is nil and return a nil []byte.
    `),

**Comment by vtopc** [comment]
Hi @behrouz-rfa. Thank you for reporting. I fixed it and added nilaway to detect such issues in the future.
