### ISSUE TITLE
Campaigns have been deprecated since development work on this SDK commenced.

### ISSUE THREAD

**Issue by Icedroid** [mailgun/mailgun-go#32]
Can I use mailgun-go CreateCampaign,UpdateCampaign etc Campaigns function ? It is deprecated?

**Comment by mbanzon** [comment]
Where have you found information about campaign deprecation?

**Comment by Icedroid** [comment]
in the source code of campaigns.go

**Comment by mbanzon** [comment]
Ah - I see it now. AFAIK the deprecation should mean that you can use is but shouldn't. We really need an official Mailgun rep. to weigh in on this - @sam-falvo ?

**Comment by sam-falvo** [comment]
My understanding is that the campaign functions were deprecated because newer API features replaced them.  What are your specific goals?  We can probably find alternative methods that work better and/or provide more metrics.
