### ISSUE TITLE
Remove dependency on github.com/go-chi/chi/v5 (again)

### ISSUE THREAD

**Issue by rhcarvalho** [mailgun/mailgun-go#322]
Hi! I'm evaluating the dependency tree of a project that uses `github.com/mailgun/mailgun-go/v4`. The project doesn't use the `MockServer`, still `github.com/go-chi/chi/v5` ends up in the dependency tree via mailgun-go.

I see this library went from chi to gorilla/mux (https://github.com/mailgun/mailgun-go/pull/252) and back to chi (https://github.com/mailgun/mailgun-go/pull/307) in the last few years.

Now with Go 1.22 ["enhanced routing patterns"](https://go.dev/doc/go1.22#enhanced_routing_patterns) there's a good chance to drop external dependencies in favor of using the standard library. For the usage I saw in those PRs the stdlib would be a good fit.

I see `go.mod` is currently at `1.13` which was before the `go` directive started to mean minimal Go toolchain version. And I didn't find any mention in the README with regards to supported Go versions. Go itself supports the last two major releases.

Would a PR to remove the external dependency be accepted? If so, should it wait until 1.23 is released?

**Comment by vtopc** [comment]
1. What's wrong with github.com/go-chi/chi or gorilla/mux? They are pretty lightweight libraries without any external dependencies.
2. The problem with the new https://go.dev/doc/go1.22#enhanced_routing_patterns is that they put both: the optional method and path into one string, so it's pretty easy to do a typo error there, e.g.:
chi's `r.Got("/foo", handler)` - is a compile error;
net/http's `r.Handle("GOT /foo", handler)` - is a runtime error, it would be detected only while running the code or in unit tests(assuming there is a 100% code coverage). Of course `r.Handle(http.MethodGet + " /foo", handler)` is an option, but now space makes sense and might be missed.

**Comment by rhcarvalho** [comment]
Hi @vtopc, thanks for the considerations.

1. Nothing wrong with those projects, they have their undeniable merits.
  
   My suggestion was based on the fact that "this lib is only relying on chi for testing and mocking" (quoting https://github.com/mailgun/mailgun-go/pull/252#issue-814233220) and when inspecting a larger dependency tree of a project it was unexpected that the Mailgun client, which should instinctively be an HTTP client, depends on a HTTP server routing library.

2. Good point. Concerns in that direction (e.g. https://github.com/golang/go/issues/61410#issuecomment-1641072070) have been raised upstream but the implementation nonetheless favored the way it was implemented, having to balance different tradeoffs.
  
   I can see how the impact on developer experience can be decisive in the context of a project whose main concern is being a web server, but it is less clear to me how it would affect testing the Mailgun client.

All that said, I don't feel strong about it and wouldn't mind if we just close this issue and move on :)

**Comment by rhcarvalho** [comment]
BTW nice to see you're picking up maintenance of the library :rocket:
