### ISSUE TITLE
Incorrect use of strconv.Unquote in messages.go

### ISSUE THREAD

**Issue by IvanWillsBI** [mailgun/mailgun-go#324]
```
func (m *Message) AddVariable(variable string, value interface{}) error {
	if m.variables == nil {
		m.variables = make(map[string]string)
	}

	j, err := json.Marshal(value)
	if err != nil {
		return err
	}

	encoded := string(j)
	v, err := strconv.Unquote(encoded)
	if err != nil {
		v = encoded
	}

	m.variables[variable] = v
	return nil
}
```
Doesn't work for boolean values or numbers (non string values, as they don't appear as ""foo"")

Therefore, in my mailgun template which uses {{#if }} handlebars, I cannot check the boolean value, as it is sent as a string

**Comment by vtopc** [comment]
Hi, @IvanWillsBI.

There is a test for boolean - https://github.com/mailgun/mailgun-go/blob/88d455cf93e9834b53564a654522ac1995120469/messages_test.go#L389
is it incorrect? I can't get why it should be `""foo""`.

**Comment by vtopc** [comment]
Closing as unreproducible. Feel free to reopen it again.
