### ISSUE TITLE
Why does this depend on chi?

### ISSUE THREAD

**Issue by asmaloney** [mailgun/mailgun-go#332]
I was surprised to see chi in my dependencies and traced it to mailgun.

What's this used for?

Could it be replaced by go 1.22's [new routing](https://go.dev/blog/routing-enhancements)?

Thanks!

**Comment by vtopc** [comment]
Hey. I replied in https://github.com/mailgun/mailgun-go/issues/322#issuecomment-2348634829

**Comment by loeffel-io** [comment]
agree

github.com/go-chi/chi/v5 v5.0.8
github.com/json-iterator/go v1.1.10

can be easily removed 

testify is pretty bloated and could be easily based on native golang stuff or https://github.com/google/go-cmp

**Comment by vtopc** [comment]
@asmaloney, I replied in https://github.com/mailgun/mailgun-go/issues/322#issuecomment-2348634829 why 1.22's [new routing](https://go.dev/blog/routing-enhancements) is bad. 
But can you write some wrapper above, e.g.:
```
type Handler struct {
    Method string
    Path string
}
```
So feel free to create a PR.

**Comment by vtopc** [comment]
@asmaloney, closing as you removed your assignment.
