### ISSUE TITLE
Missing webhook events

### ISSUE THREAD

**Issue by loeffel-io** [mailgun/mailgun-go#337]
Hello,

can you please update your docs when you deprecate

examples:

```
// Deprecated: use func NewMessage instead of method.
NewMessage(from, subject, text string, to ...string) *Message
```

no idea what i need to use here

There are several events like Rejected which i even can't find in the webhooks api, while in the docs https://www.mailgun.com/blog/product/same-api-new-tricks-get-event-notifications-just-in-time-with-webhooks/
https://help.mailgun.com/hc/en-us/articles/203661564-Events-Logs-Message-Event-Types

its pretty wild west with mailgun atm

Thanks

**Comment by loeffel-io** [comment]
> Deprecated: use func NewMessage instead of method.

Got it, make sense! never understood why we need the api client to create a message 😄

**Comment by vtopc** [comment]
> never understood why we need the api client to create a message 😄

Me too.

**Comment by vtopc** [comment]
> There are several events like Rejected which i even can't find in the webhooks api, while in the docs https://www.mailgun.com/blog/product/same-api-new-tricks-get-event-notifications-just-in-time-with-webhooks/ https://help.mailgun.com/hc/en-us/articles/203661564-Events-Logs-Message-Event-Types

Check the https://documentation.mailgun.com/

**Comment by loeffel-io** [comment]
@vtopc 

which events.Event is for the permanent_failure webhook event?

**Comment by vtopc** [comment]
> can you please update your docs when you deprecate

It is updated - https://pkg.go.dev/github.com/mailgun/mailgun-go/v4

**Comment by loeffel-io** [comment]
> which events.Event is for the permanent_failure webhook event?

can we please take care about this, this is breaking for us rn

**Comment by vtopc** [comment]
> > which events.Event is for the permanent_failure webhook event?
> 
> can we please take care about this, this is breaking for us rn

I'm waiting for the response.

But you can also ask https://www.mailgun.com/contact/support/

**Comment by vtopc** [comment]
> @vtopc
> 
> which events.Event is for the permanent_failure webhook event?

<img width="939" alt="image" src="https://github.com/user-attachments/assets/57ab7ace-1d65-4379-9679-6ccf41f24aff">

https://documentation.mailgun.com/docs/mailgun/user-manual/events/#event-types
