### ISSUE TITLE
Add Ability to Set "Reply-To"

### ISSUE THREAD

**Issue by tp** [mailgun/mailgun-go#34]
Currently I can't see a way to set a Reply-To address, which seems to be supported by the mailgun API.

**Comment by dtelyukh** [comment]
m := mailgun.NewMessage("Sender <sender@example.com>", "Subject", "Message Body", "Recipient <recipient@example.com>")
m.AddHeader("Reply-To", "tester@example.com")

**Comment by mbanzon** [comment]
I agree that it would be most useful to have a `.ReplyTo(a string)` function on the message type.

It might be worth looking into other _shorthand_ functions as well.
