### ISSUE TITLE
[BUG] Webhooks

### ISSUE THREAD

**Issue by loeffel-io** [mailgun/mailgun-go#349]
Because no one is responding to my support tickets, i try it here! 

You have several issues with your webhook api! I can confirm that because i tested it from two different independent accounts.
Its a mess and no one cares - can you please finally fix this this stuff, more infos in my support tickets.

I regret to choose mailgun.

**Comment by loeffel-io** [comment]
WTF, reported **since 2 weeks**
Same problem for the apis

![2024-11-25 16 49 52](https://github.com/user-attachments/assets/acad2da7-b9ec-47d3-aa6c-c98c3894c71a)

**Comment by vtopc** [comment]
Hi. This is not related to this SDK repo. Please get in touch with support - https://www.mailgun.com/contact/support/

**Comment by loeffel-io** [comment]
> Hi. This is not related to this SDK repo. Please get in touch with support - https://www.mailgun.com/contact/support/

😂 speechless

**Comment by vtopc** [comment]
Could you share the ling to support tickets?

**Comment by loeffel-io** [comment]
https://app.mailgun.com/support/view/3222179

**Comment by loeffel-io** [comment]
its nearly 3 weeks btw - unbelievable

**Comment by medge-mailgun** [comment]
@loeffel-io We are investigating why this ticket didn't surface to us. I'm on the team that owns the Webhooks API, among other services, so I'll take a look and try to see what might be going on here.

As stated above, the SDK repository is not the place for support ticket discussion, so we'll continue in the ticket, but I do apologize that your ticket went unanswered.

**Comment by medge-mailgun** [comment]
@loeffel-io I understand completely. We're looking into it!

**Comment by Jvb182** [comment]
@loeffel-io We're currently focused on finding out why you're receiving this response for this specific URL.

{"message":"https://emailmailgun.mindful.com/v1/projects/mindful/webhooks:receive is not a valid url"}

Is this your primary issue? Along with the frontend showing varied results upon refreshing?

**Comment by loeffel-io** [comment]
Hey, sorry, we had sleep time in my tz.

No this is by far not my primary issue.
The support answered, that my endpoint is not reachable which causes the issues - this is by fact **wrong**. It doesn't matter if the endpoint is reachable or not (tested this many many times).

There are so many issues like created webhooks (sometimes it works), aren't returned from the mailgun webhook api.
In the next api call the webhook just is there again. For me this feels like a cache issue or something similar.

**Lets start here**: created a domain, verified it, create webhook (which should work 😄):

![2024-11-26 12 57 42](https://github.com/user-attachments/assets/2c0e431e-26f6-49da-9dbc-f6a40cfdaf03)

**Comment by loeffel-io** [comment]
Check this out: 

Create new account in inkognito, create domain, add webhooks - everything is broken after this moment - looks easy to reproduce.

Doesnt matter if the account email is verified, if the account has no credit hard or the account has an active payed subscription.

**Your API is broken to everyone.**

https://gifyu.com/image/SGQPM

**Comment by Jvb182** [comment]
@loeffel-io I really appreciate you taking the time to make that GIF. Very helpful. We're looking into this on our end. Sorry that you had to wait this long to get attention, I'm trying to track down why that happened as well. 

Please stay tuned with the support ticket for updates.

**Comment by loeffel-io** [comment]
@Jvb182 @medge-mailgun i need updates 🙏

**Comment by loeffel-io** [comment]
@Jvb182 @medge-mailgun ???

**Comment by medge-mailgun** [comment]
@loeffel-io As I said above, the team responsible for working on this is not monitoring GitHub Issues so please keep communication in the support ticket, as John mentioned. The team has many competing priorities so we are doing what we can, when we can.

As a last update to this thread: The last debugging session occurred on 2024-12-05 with a few PRs in flight to try and improve the replication lag we think is the cause of your issue. We're hoping to see improvements after this change.
