### ISSUE TITLE
add ability to verify data POSTed by mailgun

### ISSUE THREAD

**Issue by rgarcia** [mailgun/mailgun-go#36]
When processing a webhook or route, you need to verify that the POST is actually coming from Mailgun. Basically this code: https://github.com/riobard/go-mailgun/blob/master/webhook.go#L89-L102.

Relatedly (and perhaps blocking this) there is no code in this library for processing routes or webhooks. I'd submit a PR but I'm curious how you'd like to see that added to the library.

**Comment by mbucc** [comment]
I'm already using this library for sending mail via MailGun and came looking if there was a type that maps to the JSON for receiving a forward that posts to a URL.

StoredMessage is close, but not a match.  (http://bin.mailgun.net/a44bcdef is an example of what is posted.)

@rgarcia, do you have this type defined?  I didn't see it in your repo.

How about naming the type ForwardedMessage?  For starters, all we need is the type annotated with json tags I think.

**Comment by rgarcia** [comment]
@mbucc I ended up defining it in my app: https://github.com/rgarcia/scheduleforlater.com/blob/afb07d58a140d78fb2858a6043ae0625ce3f21a1/server.go#L37-L56

**Comment by mbucc** [comment]
@rgarcia Thanks!  (My current plan has changed a bit; use store and notify, write a Handler and use the existing stored message struct.)
