### ISSUE TITLE
HTML mails showing incorrectly in Inbox

### ISSUE THREAD

**Issue by Dieterbe** [mailgun/mailgun-go#37]
Hi,
would it be possible to add an example of sending email that has an html and a plaintext part?
thanks.

**Comment by kyleboyle** [comment]
https://godoc.org/github.com/mailgun/mailgun-go#Message.SetHtml

**Comment by raitucarp** [comment]
I use SetHtml, and I see the email in my inbox. Why is it a quoted html instead an html email?

**Comment by kyleboyle** [comment]
What is "a quoted html"? Show us your code

**Comment by raitucarp** [comment]
Oh I use inbox by Google, it seems not compatible, it's like quoted text but html. While I open the email via gmail, it's like normal html. I'll back shortly and paste the code here, wait a minutes..

**Comment by mbanzon** [comment]
@raitucarp have you done any more testing?

I've just moved the tests around in [the APIv3 branch](https://github.com/mailgun/mailgun-go/tree/APIv3) - it should be pretty easy to run them now.

I'm not seeing any problems with HTML mails here - testing both with Inbox and Gmail - can you confirm this as well?
