### ISSUE TITLE
API v3

### ISSUE THREAD

**Issue by EtienneBruines** [mailgun/mailgun-go#41]
Is the upgrade to API v3 planned? Or is this project abandoned?

I'm not sure if there are any changes, but the URL changed, so there should be a reason for that? (at least we should update the URL mailgun-go uses.

**Comment by mbanzon** [comment]
There is a [list of changes](http://blog.mailgun.com/default-api-version-now-v3/). I'm not sure how much effort should be put in upgraded for such small changes - but it is "on the radar".

And to be clear: No - the project is not abandoned.

**Comment by fdelbos** [comment]
Hi, is this project still alive ?

**Comment by mbanzon** [comment]
Short answer: Yes

A little longer:
I don't about the resources allocated by Mailgun and/or Rackspace but I still use the code very actively - at least the parts I implemented myself. Every now and then I look at th e code with various "glasses" (mostly idiomatic, api compatibility, testing) and there is various things I would very much like to change but general lack of time (this is a spare time project) other stuff usually end up taking priority. Pull requests and bug reports are most welcome.

**Comment by fdelbos** [comment]
Thanks.

**Comment by pkieltyka** [comment]
I'm recently evaluating Mailgun to use in our infrastructure and I'm surprised to see this client drift from the mainline v3 API for over a year. Any updates..?

**Comment by mbanzon** [comment]
I have now begun working on [the APIv3 branch](https://github.com/mailgun/mailgun-go/tree/APIv3) - any help/testing/oversight would be greatly appreciated.

I'm working on making the project more idiomatic Go - the first step has been to move the tests from the `acceptance` folder into the main folder at have the project test with a regular `go test` command (no build tags needed eg.) - the tests now uses environment variables for API keys, addresses etc. (this is detailed in the README).
