### ISSUE TITLE
NewMailgun - publicApiKey

### ISSUE THREAD

**Issue by EtienneBruines** [mailgun/mailgun-go#42]
I suppose the function
```go
func NewMailgun(domain, apiKey, publicApiKey string) Mailgun {
	m := MailgunImpl{domain: domain, apiKey: apiKey, publicApiKey: publicApiKey}
	return &m
}
```
has a `publicApiKey` because the API v2 uses it? I cannot find any reference to it at the documentation / website of Mailgun, and leaving it blank enables me to send the e-mail anyway. 

What's its use? And why is it still there?

**Comment by mbanzon** [comment]
Have a look at the documentation [here](https://documentation.mailgun.com/api-email-validation.html#email-validation). The advice for these types of API calls is to use the public API key.

**Comment by discordianfish** [comment]
Same here, very confusing. So where is the public API key? I can't find that in my admin interface either.

**Comment by mbanzon** [comment]
This issue has been resolved. The public API key is used when validating email addresses. Please see the documentation linked. It seems that the public API key is linked to the account and not the domains - it can be seen on the dashboard right hand side (currently).

<img width="333" alt="screen shot 2016-10-23 at 07 52 30" src="https://cloud.githubusercontent.com/assets/2138948/19624418/f086c326-98f5-11e6-89cd-13276f31e547.png">
