### ISSUE TITLE
Webhooks Timeout

### ISSUE THREAD

**Issue by varunkumar3618** [mailgun/mailgun-go#43]
The functions to create and update webhooks time out frequently.

**Comment by mbanzon** [comment]
Sorry for the long delay.

This timeout problem seems odd - is it reproducible? There are so many factors in this that I am reluctant to consider it anything but a common connection error - an error occurring between client and server, nothing to do with the library and/or API.

Do you have any output and/or error message?

**Comment by mbanzon** [comment]
So far the tests on [the APIv3 branch](https://github.com/mailgun/mailgun-go/tree/APIv3) is running (at least here) with no problems.
