### ISSUE TITLE
Is a MailGun safe for concurrent use by multiple goroutines?

### ISSUE THREAD

**Issue by carbocation** [mailgun/mailgun-go#44]
Once initialized, for example in an init() function, is a MailGun safe for concurrent use by multiple goroutines?

**Comment by sb89** [comment]
I would like to know this too.

**Comment by zupa-hu** [comment]
Just look at the implementation. The MailgunImpl type has only immutable fields (string) and `*http.Client` which is thread safe. There are a couple of global variables, they are used as constants. Thus you are safe to use a MailGun object concurrently.

For reference, the MailgunImpl struct as of a98c4eecda3e6a36bd804ae80e9a4f8edaa6cd99

```go
type MailgunImpl struct {
	domain       string
	apiKey       string
	publicApiKey string
	client       *http.Client
}
```

**Comment by mbanzon** [comment]
Thank you for answering @zupa-hu - I'm closing this issue for now.
