### ISSUE TITLE
Configure SMTP Server

### ISSUE THREAD

**Issue by AlaRuba** [mailgun/mailgun-go#47]
Hi,

I'm a bit fuzzy on this, but I'm assuming the domain is the SMTP server. I basically have MailHog running, and I want all my e-mails to go to MailHog during development, but I can't find where to set the SMTP server that I hit.

I'm wondering if it's the domain we set when we create the mailgun.

Thanks.

**Comment by mbanzon** [comment]
You can use Mailgun as an SMTP server - but that will not help here.

The library use the API via HTTP. To switch between a local SMTP server in development and the Mailgun service (using this library) you'll have to write your own wrapper around mail sending.
