### ISSUE TITLE
Events pagination

### ISSUE THREAD

**Issue by luxifer** [mailgun/mailgun-go#52]
I'm implementing a dashboard for mailgun (https://github.com/Xotelia/mailgun-dashboard). I have a question regarding the event pagination. There is a next and previous link in event API response. But with the implementation of the API I have to request the first page and then, if we are on page ten I will have to call GetNext() 10 times. Is it possible to pass an offset to `GetEventsOptions`? And also, how the pagination works ? based on timestamp? Offset? whatever?

**Comment by mbanzon** [comment]
Sorry for the response time.

Please refer to the events part of the API documentation - as far as I can see there is no way to specify an offset. The docs will also contain the relevant information about sorting eg.
