### ISSUE TITLE
.GetStoredMessage fails with wrong URL message

### ISSUE THREAD

**Issue by fiatjaf** [mailgun/mailgun-go#58]
```go
// from a webhook handler
url := r.PostFormValue("message-url")
urlp := strings.Split(url, "/")
err := mailgun.Client.GetStoredMessage(urlp[len(urlp)-1])
```

Generates an error that reads as

```
UnexpectedResponseError
URL=https://api.mailgun.net/v2/domains/mydomain.com/messages/eyJwIjpmYWxzZSaWFwiayZDgxNzc0LWJaWFlMzItNGYS1hM2E2LTc4NzUwYWRhZjMaWF3OCIsInMiOiJkYzRjZmIiwiYyI6InNhaWFkIn0=
ExpectedOneOf=[]int{200, 202, 204}
Got=400
Error: {"message":"Please use URLs as they are given in events/webhooks"}
```

While the value of `url` was `https://si.api.mailgun.net/v3/domains/mydomain.com/messages/eyJwIjpmYWxzZSaWFwiayZDgxNzc0LWJaWFlMzItNGYS1hM2E2LTc4NzUwYWRhZjMaWF3OCIsInMiOiJkYzRjZmIiwiYyI6InNhaWFkIn0=`.

**Comment by mbanzon** [comment]
@fiatjaf this should be fixed in [the APIv3 branch](https://github.com/mailgun/mailgun-go/tree/APIv3).

**Comment by fiatjaf** [comment]
@mbanzon is that branch completely usable? How is the Mailgun support for API v3? How can I get information about this?

(I'm afraid of migrating because things can just stop working, like this same issue, which appeared suddenly and unexpectedly on my production code.)

**Comment by mbanzon** [comment]
@fiatjaf the tests run without any problems. Mailgun have migrated everything to API v3 - v2 is legacy now. As you see in your original description the "v2" is returning URLs for "v3" - that alone should be a good indicator that you should migrate asap.

If you have any tests you can run to verify integrity that would be awesome - I wouldn't recommend dumping the APIv3-branch right into production code. This should wait it is merged into `master` - at that point I've been running the code in production for some time (it is running now - no problems so far - afaik the new branch is more stable).

**Comment by mbanzon** [comment]
I'm going to merge the branch into master shortly.
