### ISSUE TITLE
package "testing" imported in non-testing code

### ISSUE THREAD

**Issue by daBrado** [mailgun/mailgun-go#63]
In `acceptance.go`, package "testing" is imported, and so is imported by anything using the mailgun go package.  (In particular, that showed up to me as the testing command line flags showing up in a main package that was using the mailgun package.)

Perhaps `acceptance.go` should instead be `acceptance_test.go`?  It seems the functions within are only used by other `*_test.go` files.

**Comment by mbanzon** [comment]
You are correct - the `acceptance.go` was simply moved into to main folder when moving the rest of the test files from the `acceptance` folder - silly mistake. Thank you for noticing - fix inbound.

**Comment by daBrado** [comment]
Thanks!
