### ISSUE TITLE
GetStoredMessage fails with "Please use URLs as they are given in events/webhooks"

### ISSUE THREAD

**Issue by daBrado** [mailgun/mailgun-go#64]
When passing in the storage.key of an event to the GetStoredMessage function, I get something like:

```
UnexpectedResponseError
URL=https://api.mailgun.net/v3/domains/example.com/messages/STORAGEKEY
ExpectedOneOf=[]int{200, 202, 204} Got=400
Error: {"message":"Please use URLs as they are given in events/webhooks"}
```

The URL provided by the event's storage.url uses a slightly different domain:

```
https://so.api.mailgun.net/v3/domains/example.com/messages/STORAGEKEY
```

Which, if followed (with proper credentials) gives the proper response.

The only difference from the URL generated by GetStoredMessage is the "so." sub-sub-domain, for what that is worth.

**Comment by mbanzon** [comment]
I see the problem - do you/we know if the domain used for stored messages is _always_ the same?

This seems very odd - the tests run - and I can't see anything strange in those.

**Comment by daBrado** [comment]
I do not know if it is always the same... though the documentation for messages says (https://documentation.mailgun.com/api-sending.html#retrieving-stored-messages):

> To retrieve an inbound message that has been stored via the `store()` action, use the URL found in the stored event (which you can find through the Events API, or in the notify webhook set when creating the store action (`store(notify="http://mydomain.com/callback")`).

...which would seem to suggest that one should use the URL as given, I think?

**Comment by daBrado** [comment]
Given the documentation quoted above, would it be preferrable to have the `StoredMessage` methods take the `url` value directly instead of the `key` value?  Trying that in a local copy of the mailgun-go repo where I just bypass the `generateStoredMessageUrl` function seems to work fine.

Or are there cases where you would have the message `key` but not its `url`, and/or is that too much of a change in expectations for the argument for those methods?

**Comment by luxifer** [comment]
I have the same problem, since stored message are not always on the main API domain, this wrapper is not able to fetch stored messages. I had to create a custom function to get the stored message by its url.

**Comment by mbanzon** [comment]
@luxifer is that something we can get into the library?

**Comment by luxifer** [comment]
I'll see. Not as is, but it is possible

Le 4 sept. 2016 5:55 PM, "Michael Banzon" <notifications@github.com> a
écrit :

**Comment by james-lawrence** [comment]
its a 4 line change to fix the GetMessage functions in the library to just take the url.

**Comment by thrawn01** [comment]
Pull requests welcome, if you have a fix.

**Comment by mbanzon** [comment]
@thrawn01 do we know if this is still an issue?
