### ISSUE TITLE
http.DefaultTransport and http.DefaultClient are not available in App Engine

### ISSUE THREAD

**Issue by alanef** [mailgun/mailgun-go#66]
When trying to use this API from Google App engine gives the errors  on m.Send

Post https://api.mailgun.net/v3/sandboxmysandbox.mailgun.org/messages: http.DefaultTransport and http.DefaultClient are not available in App Engine. See https://cloud.google.com/appengine/docs/go/urlfetch/

**Comment by alanef** [comment]
edit ... found this so will try a different approach

https://cloud.google.com/appengine/docs/flexible/go/sending-emails-with-mailgun

**Comment by mbanzon** [comment]
Have you looked at [the documentation](https://godoc.org/gopkg.in/mailgun/mailgun-go.v1#MailgunImpl.SetClient)?

**Comment by alanef** [comment]
Documentation? :)
