### ISSUE TITLE
How does the text and HTML version work?

### ISSUE THREAD

**Issue by raeesbhatti** [mailgun/mailgun-go#67]
Exploring the [Go API examples](https://documentation.mailgun.com/api-sending.html#examples). I see that the message content is added two times in second example, first time as text (when using `.newMessage()`) and second time as HTML (using `.setHTML()`). How does this work?
Which of these contents will be sent in the email? or both? or is it something else?

**Comment by mbanzon** [comment]
Basically both versions is sent. It is not specific to the library and/or Mailgun.

A quick search gave this great article from MailChimp: http://templates.mailchimp.com/concepts/how-html-email-works/

**Comment by raeesbhatti** [comment]
Cool!! I didn't know this. Thank you 🙇
