### ISSUE TITLE
Is there any way to introspect messages?

### ISSUE THREAD

**Issue by tleyden** [mailgun/mailgun-go#68]
I'm trying to mock out mailgun so that all messages get captured and can later be introspected for correct application behavior.  

Here's a snippet of the mock:

```
type MockMailGun struct {
    SentMessages chan *mailgun.Message

    // Embed the Mailgun interface. No idea what will happen if unimplemented methods are called.
    mailgun.Mailgun
}

func (mmg *MockMailGun) Send(m *mailgun.Message) (string, string, error) {
    defer func() {
        mmg.SentMessages <- m
    }()
    return "", "", nil
}
```

But I'm running into a problem when I try to look at the messages to introspect previous calls that were made to `Message.AddHeader()`, because there's no way to get the headers (or any other metadata about the message.

Here's what I'd like to be able to do:

```
func (mmg *MockMailGun) waitForNotification(nt NotificationType) {

    message := <-mmg.SentMessages
    if message.GetHeader("MyHeader") == "foo" {
        // Can't do this, no way to get header from message
    }

}
```

But there is no `message.GetHeader()` available in the API.

Is there any recommended way of doing this kind of mock or being able to introspect messages?

Hopefully this is the right place to ask this, I didn't see a link to a forum or group .. but let me know if I should post this somewhere else.

**Comment by tleyden** [comment]
Here's my workaround to introspect the headers field in case it's useful for anyone:

```

func (mmg *MockMailGun) getHeaderViaReflection(message *mailgun.Message, headerKey string) (string, error) {

	val := reflect.ValueOf(*message)
	headers := val.FieldByName("headers")

	switch headers.Kind() {
	case reflect.Map:
		for _, key := range headers.MapKeys() {
			mapVal := headers.MapIndex(key)
			switch mapVal.Kind() {
			case reflect.String:
				return fmt.Sprintf("%s", mapVal), nil
			default:
				return "error", fmt.Errorf("Unexpected type for value at key: %s", headerKey)
			}
		}

	default:
		return "error", fmt.Errorf("Unexpected type for mailgun message headers field")
	}

	return "error", fmt.Errorf("Did not find headerKey")

}

```

**Comment by mbanzon** [comment]
Sorry for the long response time.

Glad you figured out how to get the information you needed.

Could this have been solved easier at the HTTP level?

**Comment by krystalcode** [comment]
I always have a similar scenario where I want to be able to test whether a message is created with the right information by my application e.g. from, to, subject, body etc. The problem is that all fields are private and can't be accessed by the test function. Using reflection might work, but it would more straightforward if getter function would be provided.

**Comment by mbanzon** [comment]
@thrawn01 is this more easy now with the mock API you've made? Should this be implemented?

**Comment by mbanzon** [comment]
@thrawn01 it sounds too easy not to do 😏
