### ISSUE TITLE
Clarify (and rename?) API keys required

### ISSUE THREAD

**Issue by boivie** [mailgun/mailgun-go#72]
The current mailgun-go requires two keys to be specified:
 * API Key
 * Public API Key

Mailgun has recently (?) changed the names of these keys, so the "Public API Key" is now called "Email Validation Key". Also, they call the "API Key" "Active API Key". 

Maybe the docs should be updated to reflect this? 

And it would be good if it was enough to specify only the "API Key" if validation is not used in the mailgun-go API.

**Comment by mbanzon** [comment]
@boivie that seems like a good idea - the dual keys seem to cause some confusion.

**Comment by bryancallahan** [comment]
Would really appreciate this. Ran into some confusion myself just yesterday. 👍

**Comment by javiermanzano** [comment]
I have ran into same confusion today. Other sdks (like node's https://github.com/mailgun/mailgun-js) only asks for one of them.

I know I can find one of them inside domains, but where can I find the other?

Thanks

**Comment by thrawn01** [comment]
The difference between the Public and Secret API keys is poorly documented. (I'll bring it up with our UX/Documentation guys in our next meeting)
 
Let me explain how things work currently
The API keys are available on the dashboard screen when you log into your mailgun account (https://mailgun.com/app/dashboard)
![screenshot 2017-01-18 10 20 32](https://cloud.githubusercontent.com/assets/9817/22072809/184fcbde-dd69-11e6-80ef-efffc49d2176.png)

The **Public API Key** is used for Email validation See [Email Validation API Documentation](https://documentation.mailgun.com/api-email-validation.html)
The **Private API Key** is used for all other API calls

+1 to the idea of changing the name to "Email Validation Key" I would even be in favor of moving any API calls that require the Public API Key out of the `Mailgun` interface an into a separate interface. Such that mailgun-go users only need to pass in the public or private api keys into the constructor. 

```go
// Majority of the api calls
mg := mailgun.NewMailgun("example.com", "key-5c56vw23dfs42334fd")

// Email Verification
ev := mailgun.NewEmailVerification("pubkey-5c56vw23dfs42334fd")
err := ev.Verify([]string("foo@mailgun.net", "thrawn@example.com"])
```

This will break the current golang public api but I'm ok with that. Current users can continue to use `gopkg.in/mailgun/mailgun-go.v1`. After this change we will bump to v2

@mbanzon @javiermanzano @bryancallahan Thoughts?

**Comment by nikgibbens** [comment]
I have created a pull request to fix the documentation.
https://github.com/mailgun/documentation/pull/355

**Comment by alexsasharegan** [comment]
This whole thing is still confusing. Keys are labeled different across the UI and the libraries, this library doesn't specify the correct go import path, and I don't seem to get any intellisense on the mailgun types. It's a simple enough API, but it's like it's made 2x more difficult trying to wade through all this.

**Comment by thrawn01** [comment]
@alexsasharegan The use of the public and private API keys can be confusing and we have had a few internal discussions on how to improve. Outside of those discussions I've separated the use of the private and public keys in the mailgun-go library and made notes on what keys to use and where. My hope was to make things a bit clearer. 

See https://github.com/mailgun/mailgun-go/blame/master/README.md#L32-L33
and 
https://github.com/mailgun/mailgun-go/blame/master/README.md#L167-L170

If you have further suggestions we are interested in your thoughts.

**Comment by alexsasharegan** [comment]
## Regarding keys

When I visit my mailgun domain, I see these options:

- `Default Password` as a hex encoded string with format `\h{32}-\h{8}-\h{8}`
- `API Key` as a hex encoded string with format `\h{32}-\h{8}-\h{8}`

This doesn't match any of the `key-` or `pubkey-` patterns, so while I have my application code working,
this is still confusing to me.

## Regarding Imports

I know this one is a little off topic for this issue, but the readme shows importing the library like so:

```
"github.com/mailgun/mailgun-go/v3"
```

This does not resolve with the `go get` command. Removing `/v3` does work. Most libraries include the go get command at the top of their readme, and I think including a working command would be a helpful addition.

**Comment by thrawn01** [comment]
paths ending in `/3` is how golang 1.11 modules differentiate between major version changes. If you are using golang 1.10 or older or not using modules support. `go get` will not know how to pull the library properly.

See https://github.com/golang/go/wiki/Modules

I'll ask the security guys about your lack of `key-` prefix for your API key. My API key has a `key-` prefix. I'll find out and get back to you.

**Comment by alexsasharegan** [comment]
Thanks for the info on the modules. I'm up to date with go, but not using modules yet. I'll have to learn what's going on here! I imagine that's to blame for my lack of intellisense in vscode as well.

**Comment by thrawn01** [comment]
@alexsasharegan word from the security guys is that you have the new style token. I have the old style token with the `key-` prefix.

If you look at your dashboard https://app.mailgun.com/app/dashboard (once you login) You will see 'API Keys' on the bottom right, which includes the `Public Validation Key` and the `Private API Key`.

I'll change the `Public key` to  `Public Validation` in the documentation, hopefully that will avoid some of the confusion.

**Comment by alexsasharegan** [comment]
Got it. I think.

**Comment by thrawn01** [comment]
This might come up again, but until then I'm closing this.
