### ISSUE TITLE
Separate integration tests and unit tests

### ISSUE THREAD

**Issue by thrawn01** [mailgun/mailgun-go#81]
Currently travis tests will only run if the environment contains the variable `TRAVIS_SECURE_ENV_VARS` this is undesirable as some unit tests do not need an api to run.

go lang has build options which can be used to isolate tests.

Integration tests files would start with
```go
// +build integration
```

Unit test files would start with
```go
// +build unit
```

This would allow us to choose which tests to run via the command line
```bash
$ go test . -tags=unit
```

**Comment by thrawn01** [comment]
Work is in progress to move all the tests to use a mock mailgun server. This has the benefit of making our tests much more reliable although we run the risk of drifting from the Mailgun API. This apparently has occurred already even with the integration tests running against the real API. I feel like this is the better path forward. 

More work is needed to complete the transition of tests to the mock server.

**Comment by tsidei** [comment]
Hey, I'd like to continue the effort of expanding the mocks server. Any objections? If no, anything I need to know before I begin? thanks

**Comment by tsidei** [comment]
Covered all endpoints used in tests. Decided to not rewrite the message send endpoints since they can show if something changed in the API.
