### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by c2h5oh** [mailgun/mailgun-go#92]
There have been quite a few commits since 1.0.3, including tagging support when message is sent - I think it's time to tag a new minor (1.1.0) or patch (1.0.4) release - depending on whether you consider any of the changes additions or all of them are simply bugfixes.

**Comment by thrawn01** [comment]
Good point, I was holding off until I had time to work on #72 but it looks like that will be at-least a few weeks away. =(

Will tag v1.1.0

**Comment by mbanzon** [comment]
#72 would mark a good point to go to 1.1.0 - or whatever it'll be called. I have to look up the SemVer spec along with the changes actually made (you guys might know this better than me) to check for breaking changes?

**Comment by thrawn01** [comment]
#72 would need to be a 2.0 release as it breaks backward compatibility
