### ISSUE TITLE
How to use Bcc? Message is invalid

### ISSUE THREAD

**Issue by artemgrygor** [mailgun/mailgun-go#94]
Hello,
I'm trying to use this package and can't figure out how to use Bcc.

`mg := mailgun.NewMailgun(conf.Domain, conf.APIKey, conf.APIKey)
	message := mailgun.NewMessage(conf.From, subject, "Please turn on HTML version")
	for _, bcc := range to {
		fmt.Println(bcc)
		message.AddBCC(bcc)
	}

	message.SetHtml(body)

	resp, id, err := mg.Send(message)`

I'm getting error `Message in invalid`. Probably because `To` is missing.
Any ideas how to implement this please?

**Comment by c2h5oh** [comment]
Email spec requires at least one recipient to be present between to, cc and bcc, so at least in theory not setting `to` is OK, but most likely mailgun api doesn't like that, so a check has been added to this library: https://github.com/mailgun/mailgun-go/blob/master/messages.go#L566

**Comment by artemgrygor** [comment]
Hm, is it possible to run a "campaign" somehow? Or I should send email one by one?
I just don't wanna share emails with other people in this campaign.

**Comment by c2h5oh** [comment]
https://documentation.mailgun.com/user_manual.html#batch-sending

**Comment by artemgrygor** [comment]
Correct me if I'm wrong, with the batch option everyone will see each other at TO field. Is it right? I don't want to do this

**Comment by c2h5oh** [comment]
umm.. huge, highlighted in orange starting on line 4 of batch docs I linked:
````markdown
Warning It is important when using Batch Sending to also use Recipient Variables.
**This tells Mailgun to send each recipient an individual email with only their email
in the to field.** If they are not used, all recipients’ email addresses will show up in
the to field for each recipient.
````
emphasis mine.

**Comment by artemgrygor** [comment]
Oh, yep. Sorry
